= Projektauftrag
Oliver Schatzberger
1.0.0, 2021-11-18: Team: Klose Peter, Lummerstorfer Lukas, Hager Sebastian

ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// print the toc here (not at the default position)
//toc::[]

== Projektbezeichnung:

Kinoreservierung

== Projektauftraggeber:

Prof. Mag. Dr. Thomas Stütz

== Projekthintergrund:

Viele Kinos nützen für die Reservierung noch altmodische Kassenautomaten, welche jedoch sehr ineffizient und teuer sind.
Oft sieht man dies Offensichtlich an langen Schlangen vor den Kassen.

Das Projekt soll dabei Abhilfe schaffen. Indem es die Dauer verkürzt und somit den Warteschlangen entgegenwirkt.

== Projektergebnis:

Das Projekt soll am Ende mit einer grafischen Benutzeroberfläche gesteuert werden.

=== Reservierung

Die Reservierung sollte wie folgt ablaufen:

. Anmeldung
. Film aus einer Liste auswählen (nur Filme die noch Freie Plätze haben - Datenbankabfrage)
. Anzahl der gewünschten Karten auswählen (MaxWert = noch frei Plätze - Datenbankabfrage)
. simulierte Bezahlung
. Rückkehr zum Start-Screen

=== Stonierung

Die Stonierung sollte wie folgt ablaufen:

. Anmeldung
. Auswählen der Karten die man stornieren will ()
. Anzahl der gewünschten Karten auswählen (MaxWert = noch frei Plätze - Datenbankabfrage)
. Ausgabe eines Gutscheins
. Rückkehr zum Start-Screen

== Projektziel(e):

* sinnvolles anwendbares Produkt
* Pünktlichkeit

== Projektbeschreibung:

Der User soll einen Platz auswählen können auf einer Karte die in Kategorien untergeordnet ist. Er soll außerdem persönliche Daten angeben, anhand dieser wird dann der Preis berechnet. Außerdem wollen wir eine Login Funktion einbauen für wiederkehrende Nutzer.

== Meilensteine:

[options="header"]
|===
| Meilenstein / Ergebnis | Soll-Termin
| Basic Java Programm | xx.xx.yyyy
| <text> | xx.xx.yyyy
| <text> | xx.xx.yyyy
| <text> | xx.xx.yyyy
|===

== Freigaben:

-

== Projektstart:

Information folgt durch Projektauftraggeber

== Projektende:

Information folgt durch Projektauftraggeber

== Projektressourcen:

* Maven
* Java
* JavaFX
* Docker
* IntelliJ IDEA
* GitHub

== Projektrisiken:

* Performanceprobleme
* Coding-Probleme

== Projektorganisation:

* Projektleiter: Oliver Schatzberger
* Stellvertreter: Peter Klose
* Team: Lukas Lummerstorfer, Sebastian Hager

