= Projektauftrag
Oliver Schatzberger
1.0.0, 2021-11-18: Team: Klose Peter, Lummerstorfer Lukas, Hager Sebastian

ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// print the toc here (not at the default position)
//toc::[]

== Projektbezeichnung:

Kinoreservierung

== Projektauftraggeber:

Prof. Mag. Dr. Thomas Stütz

== Projekthintergrund:

Wenn ein neuer Film in die Kinos kommt, ist es sehr oft so, dass in den ersten Tagen die Filme sehr große Besucherzahlen verzeichnen.
Für die Betreiber mag es ein Vorteil sein, dass viele Besucher kommen.
Für die Kunden jedoch bedeutet ein großer Ansturm einerseits gutes(Viele Menschen wollen dort hin ich will auch dort hin) andererseits aber auch schlechtes (lange Wartezeiten und große Schlangen).

Unser Projekt wird dabei Abhilfe schaffen. Wir werden den Kunden die Möglichkeit geben, sich in aller Ruhe den Film auszusuchen und anschließend zu Bezahlen. Ohne menschlichen Kontakt, ganz simple vom Handy, Tablet, PC oder auch direkt im Kino bei den aufgestellten Automaten.

== Projektergebnis:

Das Projekt soll am Ende mit einer grafischen Benutzeroberfläche gesteuert werden.

=== Reservierung

Die Reservierung wird wie folgt ablaufen:

. Anmeldung
. Film aus einer Liste auswählen (nur Filme die noch freie Plätze haben - Datenbankabfrage)
. Anzahl der gewünschten Karten auswählen (MaxWert = noch freie Plätze - Datenbankabfrage)
. simulierte Bezahlung
. Rückkehr zum Start-Screen

=== Stornierung

Die Stornierung wird wie folgt ablaufen:

. Anmeldung
. Auswählen der Karten die man stornieren will ()
. Anzahl der gewünschten Karten auswählen (MaxWert = noch frei Plätze - Datenbankabfrage)
. Ausgabe eines Gutscheins
. Rückkehr zum Start-Screen

== Projektziel(e):

* sinnvolles anwendbares Produkt
* Pünktlichkeit

== Projektbeschreibung:

Der User soll einen Platz auswählen können auf einer Karte die in Kategorien untergeordnet ist. Er soll außerdem persönliche Daten angeben, anhand dieser wird dann der Preis berechnet. Außerdem wollen wir eine Login Funktion einbauen für wiederkehrende Nutzer.

== Meilensteine:

[options="header"]
|===
| Meilenstein / Ergebnis | Soll-Termin
| Projektstart | 04.11.2021
| Planung + Skizzen | 20.01.2022
| Erstes Demo Programm | 17.02.2022
| Datenbankanbindung | 03.03.2022
| fertiges GUI Design | 05.05.2022
| Fertiges Projekt | 16.06.2022
|===


== Projektstart:

04.11.2021

== Projektende:

16.06.2022

== Projektressourcen:

* IntelliJ IDEA
* GitHub

== Projektrisiken:

* Performanzprobleme
* Coding-Probleme

== Projektorganisation:

* Projektleiter: Oliver Schatzberger
* Stellvertreter: Peter Klose
* Team: Lukas Lummerstorfer, Sebastian Hager

