= Pflichtenheft
1.0.0, 2021-11-18: Team: Klose Peter, Oliver Schatzberger, Lummerstorfer Lukas, Hager Sebastian

ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// print the toc here (not at the default position)
//toc::[]

=== Ausgangssituation

Kinobesuche sind für viele Menschen ein wichtiger Bestandteil ihrer Freizeitgestaltung.
Genauso wie für die Schüler der HTL Leonding. Deshalb haben wir uns dazu entschlossen ein Projekt
in diesem Themenbereich durchzuführen.

=== Istzustand
----
Viele Menschen Besuchen täglich Kinos und kaufen sich Kinotickets vor Ort.
Dabei stellen sie bei den Kassen an und erwerben Tickets für die gewünschten Vorstellungen.

----
=== Problemstellung
Es gibt viele Menschen die gerne von zuhause, der Arbeit oder der Schule ihr Tickets buchen würden.

=== Aufgabenstellung
Es soll eine Applikation entwickelt werden, die es ermöglicht Tickets von überall einfach zu Buchen und
zu bezahlen. Dabei soll der Film und der gewünschte Sitzplatz einfach gewählt werden können und die Verfügbarkeit
der Auswahl stets einsichtig sein

=== Ziele
Wir wollen eine für den Benutzer einfach zu verstehende Oberfläche programmieren.
In der einfach Navigiert werden  kann und er seine Bestllungen einsehen kann.

=== Mengengerüst

=== Rahmenbedingungen
zB Vorgaben vom Auftraggeber

== Entwurf "Wie mache ich es"
=== Systemarchitektur
=== ...

== Projekthandbuch "Organisatorische Rahmenbedingungen"

* link:minutes-of-meeting.html[Protokollvorlage]
* link:demo.html[Demo]


